alibaba/AliOS-Things

build/aos_images_download.mk, build/aos_standard_targets.mk
Please refer to below comment.
=> Correct openocd log file path

build/scripts/map_parse_gcc.py
=> Fix parse map info error bug.

test/testcase/certificate_test/aos_test.c, test/testcase/certificate_test/certificate_test.mk, test/testcase/certificate_test/cutest/cut.c, test/testcase/certificate_test/rhino_test.c
-  rename certificate_test.c to aos_test.c for aos_* API test
-  add rhino_test.c for krhino_* API test
=> [certification] add krhino_* API test cases

projects/IAR/frdmkl27_yts/kernel_yts.ewp
Signed-off-by: Kong Li <li.kong@nxp.com>
=> [FRDMKL27Z IAR]Fix IAR project path issue

platform/arch/xtensa/lx106/port.c
rm debug function in ISR fucntion
=> feat(esp8266): add interrupt mark function in ISR entry function

platform/mcu/esp32/hal/gpio.c
Should free isr service related resources in hal_gpio_finalize if gpio is initialized in IRQ_MODE
=> Free isr service related resources in hal_gpio_finalize

platform/mcu/esp32/esp32.mk, platform/mcu/esp32/hal/pwm.c
An simple implementation of PWM HAL for ESP32 with 4 available channel/timer slots. Please review.
=> Initial draft of EPS32 PWM HAL

kernel/rhino/core/k_mm.c, kernel/rhino/core/k_task.c, platform/arch/xtensa/lx6/port.c
fix spinlock reentry issue in k_mm
fix task_self delete bug on esp32
=> Bug fix by HuangZhen

board/developerkit/aos/board.c, board/developerkit/aos/soc_init.c
fix #350 according to @Ray148289
=> fix developerkit linkkitapp can not work

kernel/modules/fs/fatfs/ff/include/ff.h, platform/mcu/stm32l4xx_cube/hal/hal_nand_stm32l4.c, platform/mcu/stm32l4xx_cube/hal/hal_nor_stm32l4.c, platform/mcu/stm32l4xx_cube/hal/hal_sd_stm32l4.c
bugfix: fix the sd hal compile error and fatfs error mapping
=> bugfix: fix the sd hal compile error and fatfs error mapping

board/mk3080/board.c, platform/mcu/rtl8710bn/hal/ota_port.c
1. fix an issue for Gree project not to upgrade in slow speed flash
2. ease the ota partition through the HAL flash table in board.c
=> [AliOS][hal][ota] merge OTA patch from Realtek: chenwen

framework/connectivity/coap/iotx_product_linux.c
Signed-off-by: Kun.Li <huaiming.lk@alibaba-inc.com>
=> [CoAP] Remove device secret print

kernel/modules/fs/kv/include/kvmgr.h, kernel/modules/fs/kv/kvmgr.c
[kv] enhance kv capacity for large flash (block size > 64K or total size > 64K)
=> [kv] enhance kv capacity for large flash

board/README.md
- Add evkbimxrt1050, evkmimxrt1020
Signed-off-by: Jason Yu <zejiang.yu@nxp.com>
=> [IMXRT] Add supported IMXRT boards to board.md

include/aos/kernel.h
The default app priority 32 is too high on some platform. Need a way to change AOS_DEFAULT_APP_PRI, other than editing kernel.h.
=> Able to set AOS_DEFAULT_APP_PRI during compilation.

framework/activation/ucube.py, kernel/yloop/ucube.py, site_scons/site_init.py, site_scons/toolchain.py, test/testcase/ucube.py, utility/libc/ucube.py
rvct is an old ARM compiler toolchain which is similar to KEIL's armcc, but they are not 100% compatible.
=> Support rvct toolchain in scons

platform/mcu/stm32l4xx_cube/aos/soc_impl.c, platform/mcu/stm32l4xx_cube/hal/hal_uart_stm32l4.c
Modify STACK allocate under ARMCC, add MARK for UART initialized
=> Modify STACK allocate, add MARK for UART initialized

device/sensor/drv/drv_acc_mir3_da213B.c, device/sensor/drv/drv_acc_mir3_da215.c, device/sensor/drv/drv_acc_mir3_da270.c, device/sensor/drv/drv_acc_mir3_da312B.c, device/sensor/drv/drv_acc_mir3_da380B.c, device/sensor/hal/sensor_hal.c, device/sensor/sensor.mk
Add the  driver for accelerometer of MiraMEMS：da213B、da215、da270、da312B、da380B
=> add driver for sensor

device/sensor/drv/drv_temp_humi_sensirion_sht3x.c, device/sensor/hal/sensor_hal.c, device/sensor/sensor.mk, device/sensor/ucube.py
Add support for Sensirion SHT3x (SHT30, SHT31, SHT35) humidity and temperature sensors
=> add support for Sensirion SHT3x humidity/temp sensor

board/stm32l4xx_universal/hal/hal_adc_stm32l4.h, board/stm32l4xx_universal/hal/hal_gpio_stm32l4.h, board/stm32l4xx_universal/hal/hal_i2c_stm32l4.h, board/stm32l4xx_universal/hal/hal_nand_stm32l4.h, board/stm32l4xx_universal/hal/hal_nor_stm32l4.h, board/stm32l4xx_universal/hal/hal_qspi_stm32l4.h, board/stm32l4xx_universal/hal/hal_rtc_stm32l4.h, board/stm32l4xx_universal/hal/hal_sd_stm32l4.h, board/stm32l4xx_universal/hal/hal_spi_stm32l4.h, board/stm32l4xx_universal/hal/hal_timer_stm32l4.h, board/stm32l4xx_universal/hal/hal_uart_stm32l4.h, board/stm32l4xx_universal/init/atcmd_config_platform.h, board/stm32l4xx_universal/init/board.h, board/stm32l4xx_universal/init/board_partition.c, board/stm32l4xx_universal/init/k_config.h, board/stm32l4xx_universal/init/soc_init.c, platform/mcu/stm32l4xx_cube/aos/aos.c
Add stm32l4xx_universal, which is template for user to add stm32l4xx serial mcu
=> Developer pr

platform/mcu/lpc54102/wifi_qca/license.txt
- Add the license file
Signed-off-by: Jason Yu <zejiang.yu@nxp.com>
=> [LPC54102 WIFI] Add wifi_qca stack license

board/developerkit/developerkit.mk, board/developerkit/drv/board_drv_led.c, board/developerkit/drv/board_drv_led.h, example/linkdevelop/device_ctrl/device_ctrl.c, example/linkdevelop/device_ctrl/device_ctrl.mk
* Supported Boards: developerkit, stm32l476-nucleo, stm32f412-nucleo
* Supported Boards: NXP lpc54102, TI msp432p4111launchpad
=> BugID:16953820: Device Controling based on LD

example/linkdevelop/device_ctrl/webapp/README.md, example/linkdevelop/device_ctrl/webapp/app.js, example/linkdevelop/device_ctrl/webapp/app/pages/home/index.css, example/linkdevelop/device_ctrl/webapp/app/pages/home/index.js, example/linkdevelop/device_ctrl/webapp/app/pages/not-found/index.css, example/linkdevelop/device_ctrl/webapp/app/pages/not-found/index.js, example/linkdevelop/device_ctrl/webapp/bone-config.json, example/linkdevelop/device_ctrl/webapp/package.json, example/linkdevelop/device_ctrl/webapp/public/index.html, example/linkdevelop/env_monitor/webapp/README.md, example/linkdevelop/env_monitor/webapp/app.js, example/linkdevelop/env_monitor/webapp/app/pages/home/index.css, example/linkdevelop/env_monitor/webapp/app/pages/home/index.js, example/linkdevelop/env_monitor/webapp/app/pages/not-found/index.css, example/linkdevelop/env_monitor/webapp/app/pages/not-found/index.js, example/linkdevelop/env_monitor/webapp/bone-config.json, example/linkdevelop/env_monitor/webapp/package.json, example/linkdevelop/env_monitor/webapp/public/index.html, example/linkdevelop/hmi/webapp/README.md, example/linkdevelop/hmi/webapp/app.js, example/linkdevelop/hmi/webapp/app/pages/home/index.css, example/linkdevelop/hmi/webapp/app/pages/home/index.js, example/linkdevelop/hmi/webapp/app/pages/not-found/index.css, example/linkdevelop/hmi/webapp/app/pages/not-found/index.js, example/linkdevelop/hmi/webapp/bone-config.json, example/linkdevelop/hmi/webapp/package.json, example/linkdevelop/hmi/webapp/public/index.html
=> BugID:16981187: add linkdevelop webapp demo

platform/mcu/stm32l4xx_cube/hal/hal_uart_stm32l4.c
Fix potential risk of STM32L4XX uart send mechanism
1. Use "post" mechanism to send out UART data
2. One task would not send out UART until all data of last frame send out, when the UART in READY status
3. Not block in loop only happen UART send fail
=> Fix potential risk of STM32L4XX uart send mechanism

framework/connectivity/coap/coap.mk, framework/protocol/linkkit/iotkit/hal-impl/iot-hal.mk, framework/protocol/linkkit/iotkit/iotkit.mk
No depend component alicrpto and mbedtls under no_tls
=> Dispatch alicrypto and mbedtls from build if option 'no_tls' switch on

platform/mcu/stm32l4xx_cube/hal/hal_gpio_stm32l4.c
=> Resolve GPIO Read ERROR

board/stm32l4xx_universal/init/board_partition_256k_flash_template.c
Update Board STM32L4XX Template
=> Update Board STM32L4XX Template

example/uart/README.md, example/uart/uart.c, example/uart/uart.mk, platform/mcu/esp8266/bsp/ESP8266_RTOS_SDK/include/espressif/esp8266/gpio_register.h, platform/mcu/esp8266/bsp/driver/uart.c, platform/mcu/esp8266/bsp/include/driver/uart.h, platform/mcu/esp8266/esp8266.mk, platform/mcu/esp8266/hal/gpio.c, platform/mcu/esp8266/hal/uart.c
Add the Esp8266 gpio.c from xuhongv
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/alibaba/alios-things/563)
=> Add the Esp8266 gpio.c from xuhongv

README-zh.md, README.md
fix the wrong url of linkkit in README.md
=> [doc]: modify linkkit url

device/sal/sal_sockets.c, device/sal/wifi/mk3060/mk3060.c, framework/atparser/atparser.c
1. atparser.c: fix at_read return value, fix at_worker easily buffer full issue
2. mk3060.c: add validation after at data read
3. sal_socket.c: fix sal_recvfrom len update issue
=> recent fix for atparser.c, mk3060.c, sal_socket.c

board/developerkit/audio_hal/audio.c, board/developerkit/audio_hal/audio_hal.mk, board/developerkit/audio_hal/crc16.c, board/developerkit/audio_hal/include/audio.h, board/developerkit/audio_hal/include/crc16.h, board/developerkit/audio_hal/include/isd9160.h, board/developerkit/audio_hal/isd9160.c, example/developerkitaudio/README.md, example/developerkitaudio/developerkitaudio.c, example/developerkitaudio/developerkitaudio.mk, example/developerkitaudio/k_app_config.h, example/developerkitaudio/ucube.py
In behalf of the author:  Leon <msls@qq.com>, commit as belows:
1, 0ad74f7a367238eb7ee5512c9f5096d50db4503e
2, 77eabe89ed4eafaac17951cb39e0b803df4ea15d
=> cherry-pick some audio patches by manually for developerkit

board/atsame54-xpro/board.c, example/linkdevelop/hmi/brd_same54_press_report.c, example/linkdevelop/hmi/hmi.c, example/linkdevelop/hmi/hmi.mk
1, press button sw0 will turn on/off LED0
2, press button sw0 will report press times after mqtt is ready
=> [Microchip]SAME54-Xplained-Pro support linkdevelope.hmi

platform/mcu/rda5981x/hal/uart.c
=> fix rda5981x uart recieve bug

framework/protocol/linkkit/sdk/iotx-sdk-c_clone/src/protocol/mqtt/client/mqtt_client.c
Hey guys, we need to fix this issue.
=> fix alcs got stuck issue when mqtt reconnecting

board/esp8266/esp8266.mk, build/site_scons/upload/esp32.json, build/site_scons/upload/esp8266.json, platform/mcu/esp8266/gen_crc_bin.mk
2. fix the bug that `aos upload` esp8266 & esp32 error on windows
=> 1. fix the bug that esp8266 can't compile on windows

device/sensor/hal/sensor_hal.c
=> add define SENSOR_IRQ

example/linkkit_gateway/linkkit_entry.c, example/linkkitapp/app_entry.c
Change-Id: I98afeee553a1c1760e13c49c692403af96a5ef74
=> BugID:18683049:[linkkit app]use smartconfig as default wifi provision

middleware/linkkit/sdk-c/src/protocol/alcs/alcs_api.c, middleware/linkkit/sdk-c/src/protocol/alcs/alcs_server.c
Signed-off-by: yinghao.cyh <yinghao.cyh@alibaba-inc.com>
=> fix some alcs memery leak issue

.travis.yml, board/amebaz_dev/ucube.py, board/atsame54-xpro/ucube.py, board/b_l475e/ucube.py, board/developerkit/ucube.py, board/esp32devkitc/ucube.py, board/esp8266/ucube.py, board/linuxhost/ucube.py, board/mk3060/ucube.py, board/mk3080/ucube.py, board/starterkit/ucube.py, board/stm32f429zi-nucleo/ucube.py, board/stm32l432kc-nucleo/ucube.py, board/stm32l433rc-nucleo/ucube.py, board/stm32l476rg-nucleo/ucube.py, board/stm32l496g-discovery/ucube.py, board/uno-91h/ucube.py, build/autobuild.sh
Change-Id: I279d86d67125871e6a419fdc0a5de8708c24fd23
=> fixed travis CI build problem

kernel/uspace/syscall/include/syscall_no.h, kernel/uspace/syscall/include/syscall_ops.h, kernel/uspace/syscall/ksyscall/syscall_ops.c, kernel/uspace/syscall/ksyscall/syscall_tbl.c, network/lwip/port/include/arch/cc.h, osal/include/aos/types.h, platform/arch/arm/armv7a/armcc/a7/vector_s.S, platform/arch/arm/armv7a/common/k_phymm.c, platform/arch/arm/armv7a/common/k_proc.c, platform/arch/arm/armv7a/common/k_proc.h, platform/arch/arm/armv7a/common/preamble.h, test/testcase/certificate_test/rhino_test.c
fix uprocess unload page leak
add user-defined syscall
remove repeated system call
porting lldb
=> sort out code according to code.aliyun.com

middleware/linkkit/sdk-c/src/protocol/mqtt/client/mqtt_instance.c, middleware/linkkit/sdk-c/src/services/awss/awss_notify.c, middleware/linkkit/sdk-c/src/services/linkkit/dm/dm_message.c, middleware/linkkit/sdk-c/src/services/linkkit/dm/linkkit_gateway_legacy.c, middleware/linkkit/sdk-c/src/services/linkkit/dm/linkkit_solo_legacy.c
=> bugID:20327867:fix some bugs

framework/ywss4linkkit/libywss/awss_notify.c
=> bugID:20327867:[ywss4linkkit]add len check

network/lorawan/lorawan_4_4_2/mac/LoRaMac.c, network/lorawan/lorawan_4_4_2/mac/LoRaMacHeaderTypes.h
=> BugID:28944235:Fix for potential LoRaWAN buffer overflow bug

components/wireless/lorawan/lorawan_4_4_2/mac/LoRaMac.c, components/wireless/lorawan/lorawan_4_4_2/mac/LoRaMacHeaderTypes.h
=> BugID:28944235:Fix for potential LoRaWAN buffer overflow bug (#1192)

middleware/linkkit/sdk-c/src/services/linkkit/dm/dm_message.c
=> BugID:29304869:Fix for linkkit buffer overflow issue

build/Makefile, build/scripts/flash_program.py, build/scripts/flash_program_ll.py, build/scripts/ymodem.py, build/site_scons/scons_upload.py, build/site_scons/upload/haas1000.json
add cross-platform flash programmer for haas100
=> support cross platform flash programmer of haas100

core/debug/debug_panic.c, core/debug/debug_print.c, platform/mcu/haas1000/aos/aos.c
=> support alios panic print

application/example/Config.in, application/example/tcp_demo/Config.in, application/example/tcp_demo/aos.mk, application/example/tcp_demo/appdemo.c, application/example/tcp_demo/autobuild.json, application/example/tcp_demo/k_app_config.h, application/example/tcp_demo/maintask.c, application/example/tcp_demo/server.c, application/example/tcp_demo/tcp_client.c
=> Issue: add Tcp Demo for HaaS100

.gitignore, build/scripts/templates/new_project_template/.vscode/settings.json
Create pull  request
Signed-off-by: caiyan.cai <caiyan.cai@alibaba-inc.com>
=> update .gitignore and add setting.json

application/example/mqtt_demo/app_entry.c, components/network/sal/src/sal_sockets.c, platform/board/haas100/drivers/ch395_spi.c
1、ch395 driver release sem4 memory oversize
2、when sal module add dev fail , call sal api will crash
1、fix ch395 driver release sem4 memory oversize
2、before call sal moudle funciton should see if the function is null
3、mqtt app works well when haas100 use ethernet
=> support mqtt demo on haas ethernet

application/example/BLENetConfig_demo/Config.in, application/example/BLENetConfig_demo/README.md, application/example/BLENetConfig_demo/aos.mk, application/example/BLENetConfig_demo/appdemo.c, application/example/BLENetConfig_demo/autobuild.json, application/example/BLENetConfig_demo/k_app_config.h, application/example/BLENetConfig_demo/maintask.c, application/example/Config.in
This is a feature of BLE Net Config for WI-FI.
=> Issue: add BLENetConfig demo.

application/example/mqtt_uart/Config.in, application/example/mqtt_uart/aos.mk
=> fix mqtt_demo build error

middleware/linkkit/sdk-c/examples/cJSON.c, middleware/linkkit/sdk-c/examples/cJSON.h, middleware/linkkit/sdk-c/src/tools/linkkit_tsl_convert/include/cJSON.h, middleware/linkkit/sdk-c/src/tools/linkkit_tsl_convert/src/cJSON.c, middleware/uagent/uota/src/utility/cjson/cJSON.c, middleware/uagent/uota/src/utility/cjson/cJSON.h, platform/mcu/esp8266/bsp/ESP8266_RTOS_SDK/include/json/cJSON.h, platform/mcu/rtl8710bn/sdk/component/common/utilities/cJSON.c, platform/mcu/rtl8710bn/sdk/component/common/utilities/cJSON.h, utility/cjson/cJSON.c, utility/cjson/include/cJSON.h
Change-Id: If149cf84e38657ab8003bd733ee73e0027c2402b
升级cJSON到1.7.15版本以解决部分安全漏洞
=> Update cJSON to version 1.7.15

framework/protocol/linkkit/sdk/iotx-sdk-c_clone/examples/linkkit/cJSON.c, framework/protocol/linkkit/sdk/iotx-sdk-c_clone/examples/linkkit/cJSON.h, framework/protocol/linkkit/sdk/iotx-sdk-c_clone/src/ref-impl/hal/os/ubuntu/cJSON.c, framework/protocol/linkkit/sdk/iotx-sdk-c_clone/src/ref-impl/hal/os/ubuntu/cJSON.h, framework/protocol/linkkit/sdk/iotx-sdk-c_clone/src/tools/linkkit_tsl_convert/include/cJSON.h, framework/protocol/linkkit/sdk/iotx-sdk-c_clone/src/tools/linkkit_tsl_convert/src/cJSON.c, framework/uOTA/src/utility/cjson/cJSON.c, framework/uOTA/src/utility/cjson/cJSON.h, platform/mcu/esp8266/bsp/ESP8266_RTOS_SDK/include/json/cJSON.h, platform/mcu/rtl8710bn/sdk/component/common/utilities/cJSON.c, platform/mcu/rtl8710bn/sdk/component/common/utilities/cJSON.h, utility/cjson/cJSON.c, utility/cjson/cJSON_Utils.c, utility/cjson/cJSON_Utils.h, utility/cjson/include/cJSON.h
Signed-off-by: 福明 <wuxiangnan.wxn@alibaba-inc.com>
=> Upgrade cJSON from version 1.6.0 to 1.7.15.

components/drivers/core/fbdev/include/fb.h
* change "struct fb_info" to "fd_info_t".
=> Bug fix: declaration is not visible outside of function (#1496)

hardware/board/m5stackcore2/package.yaml, hardware/board/nodemcu32s/package.yaml, hardware/chip/espressif_esp32/esp-idf/components/esp32/ld/esp32.extram.bss.ld, hardware/chip/espressif_esp32/package.yaml
=> m5stackcore2 some libs bss moved from internal dram to spiram.

hardware/chip/haas1000/hal/wifi_port.c
[Detail]
Fix whitescan bugs in hal/wifi_port.c
- CWE252: Value returned from a function is not checked for errors
before being used
- CWE125: Out-of-bounds read from a buffer
Test Pass:  <py_engine_demo
=> haas1000: fix whitescan bugs in hal/wifi_port.c

components/drivers/peripheral/flash/include/aos/flash.h, components/drivers/peripheral/flash/include/aos/flash_core.h, components/drivers/peripheral/flash/include/aos/flashpart.h, components/drivers/peripheral/flash/include/aos/flashpart_core.h, components/drivers/peripheral/flash/include/aos/hal/flash.h, components/drivers/peripheral/flash/package.yaml, components/drivers/peripheral/flash/src/flash.c, components/drivers/peripheral/flash/src/flashpart.c, components/osal_aos/include/aos/kernel.h, components/osal_aos/package.yaml, components/osal_aos/rhino/common.c
[Detail]
Improve flash driver framework.
Build Pass: <helloworld_demo@haaseduk1>
Test Pass: <helloworld_demo@haaseduk1>
=> IssueID:1526:improve flash driver framework

haas_lib_bundles/python/libraries/htb485/README.md, haas_lib_bundles/python/libraries/htb485/yuanda_htb485.py
Signed-off-by: wusheng.tws <wusheng.tws@alibaba-inc.com>
=> provide htb485 module for driver and document

haas_lib_bundles/python/libraries/zzio606/README.md, haas_lib_bundles/python/libraries/zzio606/zzio606.py
Signed-off-by: wusheng.tws <wusheng.tws@alibaba-inc.com>
=> provide zzio606 module for driver and document

components/linksdk/components/dynreg-mqtt/aiot_dynregmq_api.c, components/netmgr/activation/activation.c, components/netmgr/include/netmgr.h, components/netmgr/netdev/src/netdev_cli.c, components/netmgr/src/netmgr_service.c, components/netmgr/src/netmgr_wifi.c, components/ota/hal/ota_hal_digest.c, components/ota/hal/ota_hal_trans.c, components/ota/tools/upack_data_file.c
=> issue:1551: fix linksdk、ota、netmgr‘s whitescan error.

hardware/board/haaseduk1/startup/startup.c
Delete useless code in hardware/board/haaseduk1/startup/startup.c
=> Delete useless code, fixed #1555

components/vfs/vfs_inode.c
=> IssueID:1570: vfs supports rootdir.

components/py_engine/modules/driver/i2c.c
[Detail]
Access fails after the same I2C device is opened for more than one time.
Rootcause:
PY-engine does not open an I2C device if it is already opened.
Solution:
Permit multiple open.
Build Pass: <pyengine_demo@haaseduk1>
Test Pass: <pyengine_demo@haaseduk1>
=> IssueID:1581:access fails after the same I2C device is opened for more than one time

components/linksdk/core/aiot_mqtt_api.c
Build Pass: py_engine_demo
Test Pass: py_engine_Demo
Signed-off-by: wangchengdong.wcd <wangchengdong.wcd@alibaba-inc.com>
=> fix linksdk whitescan error

components/netmgr/src/netmgr_wifi.c
=> IssueID:1619: clean netmgr_wifi.c private info.

haas_lib_bundles/python/libraries/uln2003/README.md
[Detail]
none
Build Pass:<none>
=> IssueID:1651: modify uln2003 input from pullup to pushpull.

hardware/board/haaseduk1/README.md
=> haaseduk1: add README.md, fix #1705

hardware/board/haas100/README.md
=> haas100: add README.md, fix #1705

hardware/board/haas200/README.md
=> haas200: add README.md, fix #1705

hardware/chip/rtl872xd/README.md
=> rtl872xd: add README.md, fix #1705

hardware/chip/haas1000/README.md
=> haas1000: add README.md, fix #1705

hardware/arch/armv8m/README.md
=> armv8m: add README.md, fix #1705

hardware/arch/riscv/README.md
=> riscv: add README.md, fix #1705

components/linksdk/components/mqtt-upload/aiot_mqtt_upload_api.c, components/linksdk/core/aiot_mqtt_api.c, solutions/linksdk_demo/package.yaml
- fix linksdk_demo cannot use file system error
- fix whitescan error
- fix new white scan error
=> fix white scan error01

components/debug/package.yaml, components/debug/src/debug_lastword.h
[Detail]
fix build issue in debug lastword
=> debug: fix build issue in debug lastword, fix #1735

components/ucloud_ai/README.md
Change-Id: Ia128f04aa362ed6be8cb9af7e7227a1607ae3bd4
=> Replace OssAccessKey with XXXX

components/ai_agent/README.md
Change-Id: Ia8906bd90d52dc67b995a1ad8631d4ee606d83ce
=> Replace OSSAccessKeyId with XXXX in ai_agent module

components/amp_adapter/platform/aos/peripheral/aos_hal_pwm.c
[Detail]
only for haas200 and haaseduk1.
=> IssueID:1780:haas python pwm adapter change from hal to aos api.

hardware/board/haas100/drivers/ch395_lwip.c
[Detail]
The CH395 ethernet chip on board is unstable for some reason.
Workaround for stable ethernet connection.
Build Pass: <helloworld_demo@haas100>
Test Pass: <helloworld_demo@haas100>
=> IssueID:1701:Workaround for CH395 ethernet chip

hardware/chip/rtl872xd/arch/lwipopts.h
[Detail]
improve lwip options to fix http test faults
=> rtl872xd: improve lwip options to fix http test faults

kernel/rhino/k_mm_debug.c
- Use printk instead of printf in mm critical region, otherwise, system
will crash, specially in SMP system.
- Remove "0x" prefix before "%p", "0x" is redundant for "%p".
=> debug: improve mm debug output

hardware/chip/rtl872xd/hal/wifi_port.c
[Detail]
remove debug log in wifi connectting
=> rtl872xd: improve log

components/linksdk/portfiles/aiot_port/aos_port.c
[Detail]
improve log with ulog system
=> linksdk: improve log

hardware/board/haas200/startup/startup.c
[Detail]
Disable haas200  debug log
=> haas200: disable haas200 debug log

components/amp_adapter/platform/aos/network/aos_network.c
[Detail]
improve log with ulog system
=> amp_adapter: improve log

modules/http/http.py
[Detail]
add http python module that requires urequests module
=> py_engine: add http python module

components/devfs/include/aos/devfs.h, components/devfs/package.yaml, components/devfs/src/devfs_aos.c
=> IssueID:1866:设备驱动对VFS的适配层

components/kv/src/kv_adapt.c, components/littlefs/src/littlefs_vfs.c
[Detail]
LittleFS and KV switch to new flash API.
Build Pass: helloworld_demo@haaseduk1
Test Pass: helloworld_demo@haaseduk1
=> IssueID:1901:LittleFS and KV switch to new flash API

components/drivers/peripheral/rtc/include/aos/rtc.h, components/drivers/peripheral/rtc/include/aos/rtc_core.h, components/drivers/peripheral/rtc/package.yaml, components/drivers/peripheral/rtc/src/rtc.c
[Detail]
New RTC device driver framework.
Build Pass: helloworld_demo@haaseduk1
Test Pass: helloworld_demo@haaseduk1
=> IssueID:1909:New RTC device driver framework

solutions/ucloud_ai_demo/README.md
Change-Id: I0000e8f8b6fab1dd8f41554548b21ac975d82d8b
=> refine documentation for cloud AI solution, fixes #1923

documentation/manual/driver_development/tty_driver_development.md
[Detail]
Fix some spelling mistakes.
Build Pass: helloworld_demo@haaseduk1
Test Pass: helloworld_demo@haaseduk1
=> IssueID:1915:Improve UART driver development document

solutions/flower_demo/README.md
In the solution flower_demo, the documentation about the sensor DHT11 is
not clear enough.  So directly using a better documentation in CSDN
instead of writing it.
=> delete not clear part, fixes #1948

components/debug/src/debug_overview.c
Before this patch, only the first waiting task will be listed in debug
command.
Now add the feature to list all waiting tasks for
sem/mutex/buf_queue/queue.
=> list all waiting tasks in debug command, fixes #1961

components/ble_netconfig/blecfg_linksdk.c, documentation/quickstart/haas100_quick_start_cloud.md, solutions/auto_demo/README.md, solutions/auto_demo/data_model_basic_demo.c, solutions/flower_demo/data_model_basic_demo.c, solutions/linksdk_demo/README.md, solutions/linksdk_demo/separate_app/data_model_basic_demo.c, solutions/rfid_demo/rfid_demo.c, solutions/ucloud_ai_demo/linkkit_event.c
解决了printf输出类型不匹配的问题。
unsigned int 类型应用 %lu 进行格式化输出。
=> [HUST CSE] Fix printf type mismatch

hardware/board/haas100/drivers/mux_i2c.c
[HUST CSE]除了开头的haas_mux_i2c_init函数返回了ret，其它的函数均没有返回值，修改增加了返回值
=> [HUST CSE]Update mux_i2c.c

components/drivers/core/base/include/devicevfs/devicevfs.h, components/drivers/core/base/package.yaml
=> Clear core/base dependency

components/drivers/peripheral/wifi/package.yaml
Clean the posix dependency.
Change-Id: If7072b492f4445e0ea3742a89ed592b221dcf6f8
=> Clear wifi dependency

components/uservice/src/select.c
=> Add time.h to fix build issue

components/oss/README.md, components/ugraphics/src/jpegdec/jpegdec.c, solutions/auto_demo/README.md, solutions/flower_demo/README.md
- Don't suggest to put the sensitive info into code
- Fix potential overflow issue
=> Recent changes
