- example/coapapp/coapapp.c
- example/mqttapp/mqtt-example-b_l475e.c
- example/mqttapp/mqtt-example.c
I search the whole project and find the three places where function parameters list are immediately followed by left brace `{` without a new line.
> Uniform coding style for brace of function

- tools/cli/cli.c
Because printf relevant function provided by C library don't support long long type, CLI command `time` always returns 0. 
For more detail, see https://github.com/alibaba/AliOS-Things/issues/20
> Fix the bug that CLI command 'time' always returns 0

- framework/protocol/alink/os/platform/linux_hardware.c
Example alinkapp@linuxhost will reboot my linux host when execution shell cmd `reset` to do factory reset. It's better to exit app rather than reboot linux host.
> Exit alinkapp@linuxhost when it calls platform_sys_reboot

- kernel/modules/fs/kv/include/kvmgr.h
Replace "_key_value_h" with "_key_value_h_".
Signed-off-by: Ding Tao <miyatsu@qq.com>
> fs: kv: Fix typo on kvmgr.h

- projects/IAR/frdmkl27_yts/kernel_yts.ewp
Previous IAR project uses absolute include path, shall use relative path.
Signed-off-by: Kong Li <li.kong@nxp.com>
> [IAR]Fix IAR project using absolute include path issue

- projects/IAR/frdmkl27_yts/kernel_yts.ewp
- Shall use relative path, not absolute path for linker file.
Signed-off-by: Kong Li <li.kong@nxp.com>
> [FRDMKL27 IAR]Fix IAR project linker file issue

- .travis.yml
Fix gcc-multilib fail to install issue.
Refer to:
https://github.com/travis-ci/travis-ci/issues/5670
> travis: split apt install into multiple commands

- device/sal/include/sal_ipaddr.h
- device/sal/include/sal_sockets.h
- example/coapapp/coapapp.c
- utility/iotx-utils/hal/rhino/HAL_UDP_rhino.c
fix coapapp@b_l475e compile problem.
alios networks support lwip add SAL。if we want to use alios networks ,when should include <aos/network.h>。Don't use lwip functions or head files directly。
> fix coapapp@b_l475e compile problem

- projects/IAR/lorawanapp/lorawanapp.ewp
Project linker file should use relative path, this helps others who have different environment to build without issue.
> [lorawan] IAR project linker file uses relative path

- kernel/vfs/vfs.c
- Add macro AOS_UART for the uart instance, this
macro is uart_0 by default, application could define
in board level to override it.
Signed-off-by: Jason Yu <zejiang.yu@nxp.com>
> [VFS] Use macro to control the aos uart instance

- build/Makefile
- WSL defines enviroment variable NAME, conflict with
the build framework. This patch unexport NAME at
the beginning of Makefile
Signed-off-by: Jason Yu <zejiang.yu@nxp.com>
> [BUILD] Support build in Windows Subsystem Linux(WSL)

- board/developerkit/Src/main.c
- example/ldapp/mqtt-example.c
- example/ldapp/sensor_display.c
The sensor data can be showned on LCD, meanwhile, sensor data
can be published via mqtt. But about 20 seconds or shaking the kits
with a little time, LCD screen will be off and never be recovery back.
Root cause:
LCD RST pin will be pulled low at least 0.7 second when issue happened,
this pin also be wrong configured as Als LED, it will be pulled low if lux<=40.
Note:
RCC_OscInitStruct.PLL.PLLN need to be set as 40 instead of 65, confirm with Notion/ST
More details please find more via Aone,
https://aone.alibaba-inc.com/project/690191/issue/15774169
> [Developerkit]: Fix Black Screen issue when running ldapp

- kernel/modules/fs/kv/kvmgr.c
[kv] fix 2 bugs:
1) origin_off should be kvpos_t, not uint16_t.
2) Don't alloc BLK_SIZE memory since only ITEM_MAX_VAL_LEN bytes is required. And if BLK_SIZE is 64KB or larger, it would be difficult to get such a big free memory block.
> fix 2 bugs of kv modules

- platform/mcu/stm32l4xx_cube/aos/soc_impl.c
- platform/mcu/stm32l4xx_cube/hal/hal_uart_stm32l4.c
2 Minor Modification:
Modify STACK allocate under Keil MDK;
Add MARK for UART initialized;
which are used to make possible that generate STM32L4XX project via CubeMX.
> Modify STACK allocate, add MARK for UART initialized: aone ID 16720373

- test/testcase/certificate_test/aos_test.c
Some platform requires larger stack since its libc consumes more memory.
> Make aos_test stack size configurable 

- utility/libc/newlib_stub.c
使用GCC编译器，printf会调用 _write_r函数，_write_r调用hal_uart_send, hul_uart_send的timeout参数不能设置为0，此处改为AOS_WAIT_FOREVER
> fix printf issue in GCC environment

- device/sensor/drv/drv_gr_baro_temp_hum_bosch_bme680/bme680.c
- device/sensor/drv/drv_gr_baro_temp_hum_bosch_bme680/bme680.h
- device/sensor/drv/drv_gr_baro_temp_hum_bosch_bme680/bme680_defs.h
- device/sensor/drv/drv_gr_baro_temp_hum_bosch_bme680/drv_gr_baro_temp_hum_bosch_bme680.c
- device/sensor/drv/drv_pm_sensirion_sps30/drv_pm_sensirion_sps30.c
- device/sensor/drv/drv_pm_sensirion_sps30/sensirion_arch_config.h
- device/sensor/drv/drv_pm_sensirion_sps30/sensirion_common.c
- device/sensor/drv/drv_pm_sensirion_sps30/sensirion_common.h
- device/sensor/drv/drv_pm_sensirion_sps30/sensirion_i2c.h
- device/sensor/drv/drv_pm_sensirion_sps30/sps30.c
- device/sensor/drv/drv_pm_sensirion_sps30/sps30.h
- device/sensor/drv/drv_pm_sensirion_sps30/sps_git_version.h
- device/sensor/hal/sensor_hal.c
- device/sensor/include/sensor.h
- device/sensor/sensor.mk
- platform/mcu/esp32/hal/i2c.c
- platform/mcu/rtl8710bn/arch/typedef.h
- Issues with I2C HAL for ESP32 have been resolved and overhead reduced by introducing bulk reads.
- Added native sensor support for Sensirion SPS30 [``AOS_SENSOR_PM_SENSIRION_SPS30``] (``dev_pm_path``).
- Added native sensor support for Bosch BME680 [``AOS_SENSOR_GR_BARO_TEMP_HUM_BOSCH_BME680``] (``dev_temp_path``, ``dev_humi_path``, ``dev_baro_path``, ``dev_gas_resistance_path``).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/alibaba/alios-things/840)
> I2C HAL for ESP32 fixed, native sensor support for Sensirion SPS30 and Bosch BME680 added.

- kernel/rhino/core/k_timer.c
- kernel/uspace/u_timer.c
sync k_timer.c and utimer.c from rel_3.0.0 to aos2.0.0_qcom branch, fixed bug that may lose timer event if user register too many timer events.
> Aos2.0.0 qcom

- build/Makefile
- build/build_rules/aos_target_build.mk
- build/build_rules/aos_target_config.mk
- build/build_rules/toolchain/aos_toolchain_arc_elf32.mk
- build/build_rules/toolchain/aos_toolchain_gcc.mk
- build/build_rules/toolchain/aos_toolchain_mwdt.mk
- platform/arch/arc/Config.in
- platform/arch/arc/aos.mk
- platform/arch/arc/include/k_compiler.h
- platform/arch/arc/include/k_types.h
- platform/arch/arc/include/port.h
- platform/arch/arc/port_c.c
- platform/arch/arc/port_s.s
- platform/board/Config.in
- platform/board/nsim_em/Config.in
- platform/board/nsim_em/README.md
- platform/board/nsim_em/aos.mk
- platform/board/nsim_em/board.c
- platform/board/nsim_em/k_config.c
- platform/board/nsim_em/k_config.h
- platform/board/nsim_em/startup.c
- platform/mcu/embarc/Config.in
- platform/mcu/embarc/README.md
- platform/mcu/embarc/aos.mk
- platform/mcu/embarc/embarc_bsp.mk
- platform/mcu/embarc/hal/hal_uart.c
***This pull request add the support for Synopsys ARC Processor, Key features:***
- the initial support for Synopsys Designware ARC Processor
- the initial support for Synopsys ARC NSIM Virtual Board
- the initial support for Synopsys ARC GNU toolchain
- the initial support for Synopsys ARC MWDT toolchain
- the support code is based on embARC_bsp which is a common SDK for all Synopsys ARC-based boards.
***Basic introduction for Synopsys ARC:***
[ARC Processors](https://www.synopsys.com/designware-ip/processor-solutions/general.html): 
20 Years of Innovation Delivering Unrivaled Power-Performance Efficiency for Embedded Applications.
[NSIM](https://www.synopsys.com/dw/ipdir.php?ds=sim_nsim):
The DesignWare® ARC® nSIM Instruction Set Simulator provides an instruction accurate processor …
> add the support for Synopsys ARC processor

- components/network/http/src/http_client.c
> Fix for http client URL does not contain slash cause crash issue

- components/amp_adapter/platform/aos/network/aos_udp.c
[Detail]
In other places, the return value of inet_aton is always checked.  So
the whitescan ask for the same check here.
Solution:
Add check of the return value.
Change-Id: I7515cb248d2d75e2fd5080766d310d7496506e5d
> IssueID:1500:add check for the inet_aton

- components/amp_adapter/platform/aos/peripheral/aos_hal_gpio.c
[Detail]
When clean the buffer, use a sizeof(pointer) is not right.
Solution:
Change the pointer to its type to make sure the size if correct.
Change-Id: Ifb0a05e3fb51a9e51d99fb8a69dd867b892ca5f2
> IssueID:1503:fix wrong sizeof usage

- components/amp_adapter/platform/aos/peripheral/aos_hal_wdg.c
[Detail]
When board is 100 or k1, there is no return value is the two functions.
Solution:
Add the return value.
Change-Id: Ice748394d9bb413dda7df2f4a77930a02fa2f932
> IssueID:1515:add value return for all branches

- components/mbedtls/library/cipher.c
[Detail]
Remove dead code in library/cipher.c
CWE561: Code can never be reached because of a logical contradiction
> mbedtls: fix whitescan bug in library/cipher.c

- components/posix/src/pthread.c
- components/posix/src/temp.c
[Detail]
temp.c: CWE377: Using an insecure temporary file creation function
pthread.c CWE252: Value returned from a function is not checked for
errors before being used
> posix: fix whitescan bugs

- components/cli/src/iobox/cd.c
- components/cli/src/iobox/cp.c
- components/cli/src/iobox/ls.c
- components/cli/src/iobox/mv.c
[Detail]
fix whitescan bugs in cli/iobox
CWE476: All paths that lead to this null pointer comparison already
dereference the pointer earlier
CWE404: Leak of memory or pointers to system resources
> cli: fix whitescan bugs in cli/iobox

- components/amp_adapter/platform/aos/peripheral/aos_hal_can.c
[Detail]
In components/amp_adapter/platform/aos/peripheral/aos_hal_can.c, one
branch of the function aos_hal_can_recv  has no return value.
Solution:
add return there.
> IssueID:1545:return value when function finish

- components/amp_adapter/platform/aos/peripheral/aos_hal_rtc.c
[Detail]
In components/amp_adapter/platform/aos/peripheral/aos_hal_rtc.c, the
functions all has no return value.
Solution:
Add return value in them.
Test Pass: eduk1_dem
> IssueID:1542:return value when function finish

- components/amp_adapter/platform/aos/peripheral/aos_hal_uart.c
[Detail]
Value returned from a function is not checked for errors before being used
calling "aos_sem_new" without checking return value.
Solution:
Add check after calling the function.
> add check after calling aos_new_mutex/sem, fixed #1549

- hardware/board/haaseduk1/config/board.c
To prevent potential failure, we need to add return value check.
> add return value check when calling sensor_i2c_close, fixed #1553

- components/trace/Config/SEGGER_SYSVIEW_AliOSThings.c
[Detail]
declaration is incompatible with previous "SYSVIEW_SendTaskInfo"
(declared
at line 75)
> trace: fix whitescan bugs

- components/init/aos_init.c
[Detail]
Fix the linking error: "undefined reference to TRACE_INIT" when trace is
enabled.
> init: fix build error when trace is enabled

- components/libc_stub/compilers/gcc/sys/ioctl.h
- components/libc_stub/compilers/gcc/sys/termios.h
- components/libc_stub/newlib_stub.c
- components/libc_stub/package.yaml
[Detail]
Improve termios and ioctl to provide more POSIX compatibility.
On console printing "\r\n" is no longer converted to "\r\r\n".
Build Pass: helloworld_demo@haaseduk1
Test Pass: helloworld_demo@haaseduk1
> IssueID:1576:Improve libc_stub

- components/amp_adapter/platform/aos/aos_system.c
Change the function as void return since it is same in linux adapter
> change the function return as void, fixed #1599

- hardware/chip/haas1000/hal/audio.c
[Detail]
An argument with the wrong type was passed to a print format specifier.
Argument "playback_stream_hdl" to format specifier "%x" was expected to have type "unsigned int" but has type "void *".
Solution:
add the type declaration for it.
> Change the type of address into unsigned int to print, fixes #1604

- hardware/chip/haas1000/hal/audio.c
[Detail]
Function that returns non-void is missing a return value
Arriving at the end of a function without returning a value.
Solution:
Add return value at the end of function.
> add return value for every condition, fixed #1601

- components/udisplay/src/udisplay.c
The pointer pbuf should be dereferenced but not used directly as a
pointer.
> Fix the incorrect pointer usage, fixed #1616

- components/py_engine/modules/modbus/modbus.c
Change-Id: I8ffddeb43bfbc0903e046b2854a305879c5ad5f3
> Fix board disattach spelling error for modbus

- hardware/chip/haas1000/aos/ota_port.c
The type of param is (void*), so the expression, (void *)param, is
meaningless.  Change it to (void)param.
> Change the expression, fixes #1634

- components/amp_adapter/platform/aos/peripheral/aos_hal_pwm.c
[Detail]
pwm duty type should be float type
> pwm: convert pwm duty type to float, fix #1652

- components/py_engine/modules/driver/uart.c
> IssueID:1654:correct HaaSPython Uart return value.

- components/ramfs/src/ramfs_vfs.c
[Detail]
Remove null check "dp->vfs_dirent.d_name != NULL" for "dp->vfs_dirent.d_name" is an array.
Build Pass: <solution list>
Test Pass: <test case list>
> IssuID:1626:Comparing an array to null is not useful "dp->vfs_dirent.d_name != NULL" since the test will always evaluate as true

- components/ramfs/src/ramfs.c
[Detail]
Use strncpy() instead of strcpy().
Build Pass: <solution list>
Test Pass: <test case list>
> IssueID:1625:The called function is unsafe for security related code

- components/debug/src/debug_overview.c
[Detail]
Debug cli command prints cpu_binded/cpu_num/cpu_exec information on
multi-core cpu.
> debug: debug command print cpu information, fix #1735

- hardware/chip/haas1000/aos/ota_port.c
An enum-typed expression is used in a Boolean conditional context. The
enum type does not appear to have a distinguished false (zero) value.
Change the type as int to fix such issue.
> Change the return value type, fixed #1736

- components/posix/include/pthread.h
[Detail]
add pthread_mutex_timedlock's declaration
> posix: add pthread_mutex_timedlock's declaration, fix #1758

- components/libc_stub/newlib_stub.c
- components/posix/src/enviro.c
Use localtime/localtime_r and env apis in newlib libc, and remove
duplicate implementation in posix and newlib_stub_uspace.
> posix: support timezone and daylight in newlib libc

- haas_lib_bundles/python/docs/haas_extended_api/driver/uart.md
[Detail]
Fix documentation on UART API: on()
Improve examples in UART doc.
Build Pass: None
Test Pass: None
> IssueID:1792:Fix documentation on UART API

- components/py_engine/adapter/esp32/fs/boot.py
[Detail]
to open bt on nodemcu32s, need to do things as below.
import kv
kv.set("disable_bt", "no")
然后重启设备
> IssueID:1794:close bt on nodemcu32s on default.

- hardware/chip/haas1000/hal/uart.c
[Detail]
hal_uart_recv_II returns 0 if no data received, instead of returning EIO.
> IssueID:1832:Fix the return value of hal_uart_recv_II

- hardware/chip/haas1000/aos/aos.c
[Detail]
Disable some haas1000 bsp log
> haas1000: disable some bsp log

- solutions/py_engine_esp32_demo/activation/activation.c
源代码中未单独考虑result_start为空指针的情况。新增了两个关于result_start的if语句，判断result_start是否为空指针。如果未判断，下面调用strstr函数时可能会出现空指针参数，产生错误。
> [HUST CSE]Add two if sentences about result_start.

- solutions/audio_demo/data_model_basic_demo.c
解决了三处printf输出格式不匹配问题，对pause_state,power_state,recorder_state三个变量的声明位置进行了修改，删去了变量res不必要的初始化。
> [HUST CSE]Fix printf type mismatch

- components/cli/package.yaml
- components/cli/src/cli.c
- components/cli/src/cli_api.h
Cli doesn't depend on littlefs and posix, clean them.  And make the
other code better.
Change-Id: I14128bc2f3451cd8f97f4fde642d68759e31bd51
> Clean cli dependencies

- components/init/aos_init.c
- components/lwip/lwip2.0.0/apps/iperf/iperf_task.c
- components/lwip/lwip2.0.0/apps/ping/net_deamon.c
- components/netmgr/activation/activation.c
- components/netmgr/package.yaml
- components/netmgr/src/netmgr_ethernet.c
1. Clean the old NET_WITH_WIFI macro;
2. Clear the wifi dependency;
3. remove the debug command which is not supported;
> Use only AOS_COMP_WIFI macro
